version: 0.2

phases:
  pre_build:
    commands:
      - apk add -U jq bash
  build:
    commands:
      - terraform version
      - bash .buildspec/plan.bash
artifacts:
  files:
    - environments/**/*
